language: ruby
rvm:
  - current

env:
  global:
    # speeds up installation of html-proofer
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

# build and validate HTML files
# more info at https://github.com/gjtorikian/html-proofer
script: bundle exec jekyll build #&& bundle exec htmlproofer ./_site --alt-ignore '/.*/'

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
